# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

# Learn more about building a configuration: https://promptfoo.dev/docs/configuration/guide

description: "My eval"

prompts:
  - "Answer the following question: {{question}}"
  - "Answer the following question. I'll tip you $20 for a correct answer: {{question}}"
  - "Answer the following question.I'll tip you $200 for a correct answer: {{question}}"
  - "Answer the following question. I won;t tip you no matter what: {{question}}"

providers:
  - id: "openai:chat:gpt-4"
    config:
      temperature: 1.0
      max_tokens: 1000
      apiKeyEnvar: OPENAI_API_KEY

tests:
  - vars:
      question: "what is type-Ia supernova?"
